<?php

declare(strict_types=1);

namespace Tests\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

final class CreateUnitTestCommand extends Command
{


    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int|void
     */
    protected function execute(InputInterface $input, OutputInterface $output): void
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
