---
- name: Update apt
  apt:
    name: software-properties-common
    state: latest

- name: Add the ondrej/php repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Install php 7.4 and dev tools
  apt:
    pkg:
      - php7.4
      - pkg-php-tools
      - php-dev
      - php-amqp
    state: latest

- name: Install composer
  apt:
    name: composer
    state: latest
