---
version: "3.7"

services:
  cli:
    build:
      context: ./
      dockerfile: ./tools/docker/cli/Dockerfile
    environment:
      SYMFONY_CACHE_DIR: /cache
    volumes:
      - type: tmpfs
        target: /cache
  phpunit:
    build:
      context: ./
      dockerfile: ./tools/docker/phpunit/Dockerfile
    environment:
      PHPUNIT_RESULT_CACHE: '/cache/.phpunit.result.cache'
    volumes:
      - .:/phpunit
      - type: tmpfs
        target: /cache
  security-check:
    build:
      context: ./
      dockerfile: tools/docker/security-check/Dockerfile
    volumes:
      - .:/security-check