---
version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.8.1
    expose:
      - 5672
    networks:
      - amqp_consumers
      - amqp_senders

  cli:
    build:
      context: ./
      dockerfile: ./tools/docker/cli/Dockerfile
    environment:
      SYMFONY_CACHE_DIR: /cache
      MESSENGER_TRANSPORT_DSN: 'amqp://guest:guest@rabbitmq:5672/%2f/messages'
    volumes:
      - type: tmpfs
        target: /cache
    networks:
      - amqp_senders
    depends_on:
      - rabbitmq
  consumer:
    build:
      context: ./
      dockerfile: tools/docker/consumer/Dockerfile
    environment:
      APP_ENV: test
      SYMFONY_CACHE_DIR: /cache
      MESSENGER_TRANSPORT_DSN: 'amqp://guest:guest@rabbitmq:5672/%2f/messages'
    volumes:
      - type: tmpfs
        target: /cache
    networks:
      - amqp_consumers
    depends_on:
      - rabbitmq
networks:
  amqp_consumers:
  amqp_senders: