---
parameters:
  env(MESSENGER_TRANSPORT_DSN): 'amqp://guest:guest@amqp:5672/%2f/messages'
framework:
  secret: '%env(string:APP_SECRET)%'
  #csrf_protection: true
  #http_method_override: true

  #esi: true
  #fragments: true
  php_errors:
    log: true