---
parameters:
  env(MESSENGER_TRANSPORT_DSN): 'amqp://guest:guest@amqp:5672/%2f/messages'
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '%kernel.project_dir%/src/*'
    exclude: '%kernel.project_dir%/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
  Shrikeh\TestSymfonyApp\:
    resource: '%kernel.project_dir%/lib/*'